##############################################################################
# SPRINTER – produkční prostředí
# Citlivé hodnoty načítat z proměnných prostředí nebo Vault!
##############################################################################
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sprinter}
    username: ${DB_USER:sprinter}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: false
  thymeleaf:
    cache: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      cookie:
        secure: true    # HTTPS

sprinter:
  security:
    remember-me-key: ${REMEMBER_ME_KEY:change-this-in-production}

logging:
  level:
    com.sprinter: INFO
    root: WARN
  file:
    name: /var/log/sprinter/sprinter.log
